<?php
/**
 * BenefitPlanTypeEnumTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  MergeHRISClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace MergeHRISClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * BenefitPlanTypeEnumTest Class Doc Comment
 *
 * @category    Class
 * @description * &#x60;MEDICAL&#x60; - MEDICAL * &#x60;HEALTH_SAVINGS&#x60; - HEALTH_SAVINGS * &#x60;INSURANCE&#x60; - INSURANCE * &#x60;RETIREMENT&#x60; - RETIREMENT * &#x60;OTHER&#x60; - OTHER
 * @package     MergeHRISClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class BenefitPlanTypeEnumTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "BenefitPlanTypeEnum"
     */
    public function testBenefitPlanTypeEnum()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
