<?php
/**
 * TimeOffApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  MergeHRISClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace MergeHRISClient\Test\Api;

use \MergeHRISClient\Configuration;
use \MergeHRISClient\ApiException;
use \MergeHRISClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TimeOffApiTest Class Doc Comment
 *
 * @category Class
 * @package  MergeHRISClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TimeOffApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for timeOffCreate
     *
     * .
     *
     */
    public function testTimeOffCreate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for timeOffList
     *
     * .
     *
     */
    public function testTimeOffList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for timeOffMetaPostRetrieve
     *
     * .
     *
     */
    public function testTimeOffMetaPostRetrieve()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for timeOffRetrieve
     *
     * .
     *
     */
    public function testTimeOffRetrieve()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
